### PR TITLE
fix(MooLite): Fix UI inconsistencies

### LINKED ISSUE #70: Empty white space when browser dimensions are in high ratios.
**Describe the bug**
An empty white space appears next to the plugin utility bar when the browser dimensions are either very wide or very tall (for example, split screening two browser windows). It appears regardless of whether one of the plugin menus is open. It is not always the same size as the menu. 

**To Reproduce**
1. Be on 'https://www.milkywayidle.com/game'
2. Snap browser window to half-screen or other weird dimensions.
3. See error

**Expected behavior**
I didn't expect to see the plugin creating empty space.

**Screenshots**
chrome
chrome 3
firefox 3
firefox

**Browser**
Chrome Version 113.0.5672.64 (Official Build) (64-bit)
Firefox 112.0.2 (64-bit)

**Additional context**
Other browser extensions do not seem to affect this bug. No other Tampermonkey scripts are installed or active.

### PR DESCRIPTION
**Pull request by LagunaElectric**
In this PR I've done the following:

- Remove the body styling from the global CSS.
  - This was part of the cause of the whitespace issue. Before making this change, the whitespace would simply appear to the right of MooLite after I moved it's mount point.
- Moved the mount point from the body to the `#root` element as the last child.
- Changed `overflow-scroll` to `overflow-clip` on MooLites wrapping div.
  - This got rid of the invisible scroll bar at the bottom and side.
- Added `overflow-auto` to the icon gutter and plugin tab.
  - This gives us a clean look, but still allows us to scroll if necessary. Also fixes a bug where the entire MooLite UI scrolled if either of those containers overflowed.
- Added `shrink-0` to the icon gutter.
  - This fixed a bug where the gutter would sometimes be squished or pushed off screen if the plugin tab was too wide.

Closes #70

### CODE REVIEW

**Comment by LagunaElectric** [comment]
@Ishadijcks Do you mind if I make the icons a little larger as well?

**Comment by Ishadijcks** [comment]
Closes #70

If you put that in the pull request body, the issue gets closed automatically when the pr is merged, handy!

**Comment by AS-Laguna** [comment]
> Closes #70
> 
> If you put that in the pull request body, the issue gets closed automatically when the pr is merged, handy!

Oh thanks for that!

File: src/main.ts [hunk 1]
```diff
@@ -68,7 +68,11 @@ const launchMooLite = () => {
         app.mount(
             (() => {
                 const app = document.createElement("div");
-                document.body.append(app);
+                const root = document.getElementById("root");
+                console.log(document.body.classList);
```
Comment (Ishadijcks) [inline src/main.ts:72]: Remove console.log

**Comment by LagunaElectric** [comment]
Done. Thanks!

File: src/main.ts [hunk 2]
```diff
@@ -68,7 +68,11 @@ const launchMooLite = () => {
...
+                root?.append(app);
```
Comment (Ishadijcks) [inline src/main.ts:73]: Instead of having root possibly be null, can you add something like

```ts
if (root == null) {
  throw new Error("Could not append MooLite to the element with id 'root' as it does not exist");
}
```

**Review by Ishadijcks — CHANGES_REQUESTED** [review]
Thank you for your first pull request!

It looks nice and clean, just 2 small comments and we can merge it

File: src/main.ts (hunk 1 above)
Comment (LagunaElectric) [reply src/main.ts:72]: Oh shit, yea 😓

File: src/main.ts (hunk 2 above)
Comment (LagunaElectric) [reply src/main.ts]: Done

**Review by Ishadijcks — APPROVED** [review]
LGTM

Congratulations on getting your first PR merged 🥳
